export const LOGIN_FETCH = 'LOGIN_FETCH';
export const LOGIN_DATA = 'LOGIN_DATA';
export const LOGOUT_FETCH = 'LOGOUT_FETCH';
export const LOGOUT_DATA = 'LOGOUT_DATA';

export const GET_USERS_FETCH = 'GET_USERS_FETCH';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_DATA_BY_FILTER_FETCH = 'GET_DATA_BY_FILTER_FETCH';
export const GET_USERS_BY_LABELS_FETCH = 'GET_USERS_BY_LABELS_FETCH';

export const GET_USERS_PENDING_DOCUMENTS_FETCH = 'GET_USERS_PENDING_DOCUMENTS_FETCH';
export const GET_USERS_PENDING_DOCUMENTS_DATA = 'GET_USERS_PENDING_DOCUMENTS_DATA';
export const FILTER_USERS_VERIFIED_DOCUMENTS = 'FILTER_USERS_VERIFIED_DOCUMENTS';

export const GET_CURRENT_USER_FETCH = 'GET_CURRENT_USER_FETCH';
export const GET_CURRENT_USER_DATA = 'GET_CURRENT_USER_DATA';
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR';
export const CURRENT_USER_RESET = 'CURRENT_USER_RESET';

export const GET_USER_DATA_FETCH = 'GET_USER_DATA_FETCH';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';

export const DELETE_USER_LABEL_FETCH = 'DELETE_USER_LABEL_FETCH';
export const ADD_USER_LABEL_FETCH = 'ADD_USER_LABEL_FETCH';
export const EDIT_USER_LABEL_FETCH = 'EDIT_USER_LABEL_FETCH';

export const GET_PERMISSIONS_FETCH = 'GET_PERMISSIONS_FETCH';
export const GET_PERMISSIONS_SUCCESS = 'GET_PERMISSIONS_SUCCESS';
export const EDIT_PERMISSION_FETCH = 'EDIT_PERMISSION_FETCH';
export const ADD_PERMISSION_FETCH = 'ADD_PERMISSION_FETCH';
export const DELETE_PERMISSION_FETCH = 'DELETE_PERMISSION_FETCH';

export const GET_FEES_FETCH = 'GET_FEES_FETCH';
export const GET_FEES_SUCCESS = 'GET_FEES_SUCCESS';
export const ADD_FEES_FETCH = 'ADD_FEES_FETCH';
export const EDIT_FEES_FETCH = 'EDIT_FEES_FETCH';
export const DELETE_FEES_FETCH = 'DELETE_FEES_FETCH';

export const GET_RESTRICTION_FETCH = 'GET_RESTRICTION_FETCH';
export const GET_RESTRICTION_SUCCESS = 'GET_RESTRICTION_SUCCESS';
export const ADD_RESTRICTION_FETCH = 'ADD_RESTRICTION_FETCH';
export const EDIT_RESTRICTION_FETCH = 'EDIT_RESTRICTION_FETCH';
export const DELETE_RESTRICTION_FETCH = 'DELETE_RESTRICTION_FETCH';

export const CHANGE_USER_STATE_FETCH = 'CHANGE_USER_STATE_FETCH';
export const CHANGE_USER_ROLE_FETCH = 'CHANGE_USER_ROLE_FETCH';
export const CHANGE_USER_OTP_FETCH = 'CHANGE_USER_OTP_FETCH';
export const CHANGE_EDIT_MODE = 'CHANGE_EDIT_MODE';
export const CHANGE_USER_PROFILE_FETCH = 'CHANGE_USER_PROFILE_FETCH';

export const SIGN_IN_REQUIRE_2FA = 'SIGN_IN_REQUIRE_2FA';

export const ALERT_DELETE = 'ALERT_DELETE';
export const ALERT_DATA = 'ALERT_DATA';
export const ALERT_PUSH = 'ALERT_PUSH';
export const ALERT_DELETE_BY_INDEX = 'ALERT_DELETE_BY_INDEX';

export const USER_ACTIVITY_FETCH = 'USER_ACTIVITY_FETCH';
export const USER_ACTIVITY_DATA = 'USER_ACTIVITY_DATA';

export const GET_ORDERS_FETCH = 'OPEN_ORDERS_FETCH';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const CANCEL_ORDERS_FETCH = 'CANCEL_ORDERS_FETCH';

export const GET_BUY_ORDERS_FETCH = 'GET_BUY_ORDERS_FETCH';
export const GET_BUY_ORDERS_SUCCESS = 'GET_BUY_ORDERS_SUCCESS';
export const GET_SELL_ORDERS_FETCH = 'GET_SELL_ORDERS_FETCH';
export const GET_SELL_ORDERS_SUCCESS = 'GET_SELL_ORDERS_SUCCESS';
export const CANCEL_BUY_ORDER_FETCH = 'CANCEL_BUY_ORDER_FETCH';
export const CANCEL_SELL_ORDER_FETCH = 'CANCEL_SELL_ORDER_FETCH';

export const GET_TRADES_FETCH = 'GET_TRADES_FETCH';
export const GET_TRADES_SUCCESS = 'GET_TRADES_SUCCESS';

export const GET_WITHDRAWALS_FETCH = 'GET_WITHDRAWALS_FETCH';
export const GET_WITHDRAWALS_SUCCESS = 'GET_WITHDRAWALS_SUCCESS';
export const UPDATE_WITHDRAW_MXN_FETCH = 'UPDATE_WITHDRAW_MXN_FETCH';

export const GET_PENDING_WITHDRAWALS_FETCH = 'GET_PENDING_WITHDRAWALS_FETCH';
export const GET_PENDING_WITHDRAWALS_SUCCESS = 'GET_PENDING_WITHDRAWALS_SUCCESS';

export const GET_WITHDRAWALS_MXN_FETCH = 'GET_WITHDRAWALS_MXN_FETCH';
export const GET_WITHDRAWALS_MXN_SUCCESS = 'GET_WITHDRAWALS_MXN_SUCCESS';

export const GET_PENDING_WITHDRAWALS_MXN_FETCH = 'GET_PENDING_WITHDRAWALS_MXN_FETCH';
export const GET_PENDING_WITHDRAWALS_MXN_SUCCESS = 'GET_PENDING_WITHDRAWALS_MXN_SUCCESS';
export const UPDATE_WITHDRAW_PENDING_MXN_FETCH = 'UPDATE_WITHDRAW_PENDING_MXN_FETCH';

export const GET_WITHDRAW_DETAILS_FETCH = 'GET_WITHDRAW_DETAILS_FETCH';
export const GET_WITHDRAW_DETAILS_SUCCESS = 'GET_WITHDRAW_DETAILS_SUCCESS';
export const ACTION_WITHDRAW_FETCH = 'ACTION_WITHDRAW_FETCH';
export const PROCESS_WITHDRAW_FIAT_FETCH = 'PROCESS_WITHDRAW_FIAT_FETCH';

export const GET_DEPOSITS_FETCH = 'GET_DEPOSITS_FETCH';
export const GET_DEPOSITS_SUCCESS = 'GET_DEPOSITS_SUCCESS';
export const GET_DEPOSITS_MXN_FETCH = 'GET_DEPOSITS_MXN_FETCH';
export const GET_DEPOSITS_MXN_SUCCESS = 'GET_DEPOSITS_MXN_SUCCESS';
export const GET_DEPOSIT_DETAILS_FETCH = 'GET_DEPOSIT_DETAILS_FETCH';
export const GET_DEPOSIT_DETAILS_SUCCESS = 'GET_DEPOSITS_DETAILS_SUCCESS';
export const ACTION_DEPOSIT_FETCH = 'ACTION_DEPOSIT_FETCH';
export const ADD_DEPOSIT_FETCH = 'ADD_DEPOSIT_FETCH';
export const UPDATE_DEPOSIT_MXN_FETCH = 'UPDATE_DEPOSIT_MXN_FETCH';

export const GET_ADJUSTMENTS_FETCH = 'GET_ADJUSTMENTS_FETCH';
export const GET_ADJUSTMENTS_SUCCESS = 'GET_ADJUSTMENTS_SUCCESS';
export const GET_ADJUSTMENTS_DETAILS_FETCH = 'GET_ADJUSTMENTS_DETAILS_FETCH';
export const GET_ADJUSTMENTS_DETAILS_SUCCESS = 'GET_ADJUSTMENTS_DETAILS_SUCCESS';
export const ACTION_ADJUSTMENT_FETCH = 'ACTION_ADJUSTMENT_FETCH';
export const ADD_ADJUSTMENT_FETCH = 'ADD_ADJUSTMENT_FETCH';

export const ADMIN_ACTIVITY_FETCH = 'ADMIN_ACTIVITY_FETCH';
export const ADMIN_ACTIVITY_DATA = 'USER_ACTIVITY_DATA';

export const GET_MEMBER_DETAILS_FETCH = 'GET_MEMBER_DETAILS_FETCH';
export const GET_MEMBER_DETAILS_SUCCESS = 'GET_MEMBER_DETAILS_SUCCESS';

export const METRICS_FETCH = 'METRICS_FETCH';
export const METRICS_DATA = 'METRICS_DATA';

export const WITHDRAWS_LIST_DATA = 'withdrawList/WITHDRAWS_LIST_DATA';
export const WITHDRAWS_LIST_FETCH = 'withdrawList/WITHDRAWS_LIST_FETCH';

export const WITHDRAWS_INFO_DATA = 'withdrawInfo/WITHDRAWS_INFO_DATA';
export const WITHDRAWS_INFO_FETCH = 'withdrawInfo/WITHDRAWS_INFO_FETCH';

export const WITHDRAWS_USER_HISTORY_DATA = 'withdrawUserHistory/WITHDRAWS_USER_HISTORY_DATA';
export const WITHDRAWS_USER_HISTORY_FETCH = 'withdrawUserHistory/WITHDRAWS_USER_HISTORY_FETCH';

export const GET_ASSETS_FETCH = 'GET_ASSETS_FETCH';
export const GET_ASSETS_SUCCESS = 'GET_ASSETS_SUCCESS';

export const GET_CURRENCIES_FETCH = 'GET_CURRENCIES_FETCH';
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_DETAILS_FETCH = 'GET_CURRENCIES_DETAILS_FETCH';
export const GET_CURRENCIES_DETAILS_SUCCESS = 'GET_CURRENCIES_DETAILS_SUCCESS';
export const ADD_CURRENCIES_FETCH = 'ADD_CURRENCIES_FETCH';
export const EDIT_CURRENCIES_FETCH = 'EDIT_CURRENCIES_FETCH';

export const GET_MARKETS_FETCH = 'GET_MARKETS_FETCH';
export const GET_MARKETS_SUCCESS = 'GET_MARKETS_SUCCESS';
export const GET_MARKETS_DETAILS_FETCH = 'GET_MARKETS_DETAILS_FETCH';
export const GET_MARKETS_DETAILS_SUCCESS = 'GET_MARKETS_DETAILS_SUCCESS';
export const ADD_MARKETS_FETCH = 'ADD_MARKETS_FETCH';
export const EDIT_MARKETS_FETCH = 'EDIT_MARKETS_FETCH';

export const GET_BLOCKCHAINS_FETCH = 'GET_BLOCKCHAINS_FETCH';
export const GET_BLOCKCHAINS_SUCCESS = 'GET_BLOCKCHAINS_SUCCESS';
export const GET_BLOCKCHAINS_DETAILS_FETCH = 'GET_BLOCKCHAINS_DETAILS_FETCH';
export const GET_BLOCKCHAINS_DETAILS_SUCCESS = 'GET_BLOCKCHAINS_DETAILS_SUCCESS';
export const ADD_BLOCKCHAINS_FETCH = 'ADD_BLOCKCHAINS_FETCH';
export const EDIT_BLOCKCHAINS_FETCH = 'EDIT_BLOCKCHAINS_FETCH';

export const GET_WALLETS_FETCH = 'GET_WALLETS_FETCH';
export const GET_WALLETS_SUCCESS = 'GET_WALLETS_SUCCESS';
export const GET_WALLETS_DETAILS_FETCH = 'GET_WALLETS_DETAILS_FETCH';
export const GET_WALLETS_DETAILS_SUCCESS = 'GET_WALLETS_DETAILS_SUCCESS';
export const ADD_WALLETS_FETCH = 'ADD_WALLETS_FETCH';
export const EDIT_WALLETS_FETCH = 'EDIT_WALLETS_FETCH';

export const GET_LIABILITIES_FETCH = 'GET_LIABILITIES_FETCH';
export const GET_LIABILITIES_SUCCESS = 'GET_LIABILITIES_SUCCESS';

export const GET_REVENUES_FETCH = 'GET_REVENUES_FETCH';
export const GET_REVENUES_SUCCESS = 'GET_REVENUES_SUCCESS';

export const GET_EXPENSES_FETCH = 'GET_EXPENSES_FETCH';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';

export const GET_CLIENT_FETCH = 'GET_CLIENT_FETCH';
export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS';

export const GET_KIND_FETCH = 'GET_KIND_FETCH';
export const GET_KIND_SUCCESS = 'GET_KIND_SUCCESS';

export const GET_GATEWAY_FETCH = 'GET_GATEWAY_FETCH';
export const GET_GATEWAY_SUCCESS = 'GET_GATEWAY_SUCCESS';

export const GET_MEMBER_DATA_FETCH = 'GET_MEMBER_DATA_FETCH';
export const GET_MEMBER_DATA_SUCCESS = 'GET_MEMBER_DATA_SUCCESS';

export const GET_MEMBER_GROUP_FETCH = 'GET_MEMBER_GROUP_FETCH';
export const GET_MEMBER_GROUP_SUCCESS = 'GET_MEMBER_GROUP_SUCCESS';

export const GET_BANK_ACCOUNTS_FETCH = 'GET_BANK_ACCOUNTS_FETCH';
export const GET_BANK_ACCOUNTS_SUCCESS = 'GET_BANK_ACCOUNTS_SUCCESS';

export const ACTION_BANK_ACCOUNTS_FETCH = 'ACTION_BANK_ACCOUNTS_FETCH';
export const ADD_BANK_ACCOUNTS_FETCH = 'ADD_BANK_ACCOUNTS_FETCH';

export const GET_BANK_ACCOUNTS_DETAILS_FETCH = 'GET_BANK_ACCOUNTS_DETAILS_FETCH';
export const GET_BANK_ACCOUNTS_DETAILS_SUCCESS = 'GET_BANK_ACCOUNTS_DETAILS_SUCCESS';
